### ISSUE TITLE
GC Safe?

### ISSUE THREAD

**Issue by akbcode** [GULPF/nimquery#3] opened 2019-04-18 16:47 UTC
I'm trying to use this in a thread and getting a not GC safe error.

I think the forward declaration of satisfies(line 642) needs to be marked gcsafe.

**Comment by GULPF** [comment] 2019-04-18 21:38
Thanks for the bug report, you are correct about the cause. I've pushed the fix and bumped the version, so should be ok now.

**Closed by GULPF** 2019-04-18 21:38 UTC
